services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzPlatform\BlockTagAttributeType\Form\Type\TagAttributeTypeType:
        tags:
            - { name: form.type }

    EzPlatform\BlockTagAttributeType\Block\Attribute\TagAttributeTypeMapper:
        tags:
            - { name: ezplatform.page_builder.attribute_form_type_mapper, alias: tags }